#!/bin/bash
# Quick deploy script with updated ECR images
# Generated by push-to-ecr.sh on Thu Nov 20 16:49:36 UTC 2025

ECR_REGISTRY="058264135704.dkr.ecr.us-east-2.amazonaws.com"
AWS_REGION="us-east-2"
AWS_ACCOUNT_ID="058264135704"

echo "Deploying with ECR images from ${ECR_REGISTRY}"

# Update and apply NIXL benchmark
sed -i "s|<AWS_ACCOUNT_ID>|058264135704|g" examples/nixl-benchmark-deployment.yaml
sed -i "s|nixl-aligned:.*|nixl-aligned:0.7.1-nccl|g" examples/nixl-benchmark-deployment.yaml
kubectl apply -f examples/nixl-benchmark-deployment.yaml

echo "✓ Deployment complete!"
echo "Check status with: kubectl get pods -l app=nixl-benchmark"
