# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Dynamo TensorRT-LLM Disaggregated Inference Deployment - FULL VARIANT (WORKING)
# Model: Qwen/Qwen2.5-0.5B-Instruct
# Architecture: 2 Prefill Workers + 2 Decode Workers + 1 Frontend
# Total GPUs: 4 (1 per worker pod)
# Image: dynamo-trtllm:full (includes development tools and complete libraries)
#
# CRITICAL CONFIGURATIONS FOR DISAGGREGATED MODE:
# 1. Workers require --extra-engine-args pointing to YAML config with cache_transceiver_config
# 2. Frontend requires DYN_ROUTER_MODE=kv environment variable
# 3. Config files mounted via ConfigMap (trtllm-config)
#
# Prerequisites:
# - ConfigMap 'trtllm-config' with trtllm-prefill-config.yaml and trtllm-decode-config.yaml
#   kubectl create configmap trtllm-config -n dynamo-cloud \
#     --from-file=trtllm-prefill-config.yaml \
#     --from-file=trtllm-decode-config.yaml

apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: trtllm-disagg-qwen-full
  namespace: dynamo-cloud
spec:
  services:
    # Frontend component - routes requests and streams responses
    Frontend:
      dynamoNamespace: trtllm-disagg-qwen-full
      componentType: frontend
      replicas: 1
      extraPodSpec:
        mainContainer:
          image: 058264135704.dkr.ecr.us-east-2.amazonaws.com/dynamo-trtllm:full
          imagePullPolicy: IfNotPresent
      envs:
        - name: DYN_ROUTER_MODE
          value: "kv"

    # Prefill Workers - process input tokens and generate KV cache
    TrtllmPrefillWorker:
      dynamoNamespace: trtllm-disagg-qwen-full
      componentType: worker
      subComponentType: prefill
      replicas: 2
      resources:
        limits:
          gpu: "1"
        requests:
          gpu: "1"
          memory: "16Gi"
          cpu: "4"
      extraPodSpec:
        mainContainer:
          image: 058264135704.dkr.ecr.us-east-2.amazonaws.com/dynamo-trtllm:full
          imagePullPolicy: IfNotPresent
          workingDir: /workspace/examples/backends/trtllm
          command:
          - /bin/bash
          - -c
          args:
            - |
              # Patch Triton's driver.py to handle non-UTF-8 characters in ldconfig output
              TRITON_DRIVER="/opt/venv/lib/python3.12/site-packages/triton/backends/nvidia/driver.py"
              if [ -f "$TRITON_DRIVER" ]; then
                echo "Patching Triton driver.py for Unicode handling..."
                sed -i 's/subprocess\.check_output(\[.\/sbin\/ldconfig., .-p.\])\.decode()/subprocess.check_output(["\/sbin\/ldconfig", "-p"]).decode("utf-8", errors="replace")/g' "$TRITON_DRIVER"
                echo "Patch applied successfully"
              fi
              # Start the TRT-LLM prefill worker with config file containing cache_transceiver_config
              exec python3 -m dynamo.trtllm \
                --model-path Qwen/Qwen2.5-0.5B-Instruct \
                --disaggregation-mode prefill \
                --extra-engine-args /config/trtllm-prefill-config.yaml
          volumeMounts:
          - name: trtllm-config
            mountPath: /config
            readOnly: true
        volumes:
        - name: trtllm-config
          configMap:
            name: trtllm-config
      envs:
        - name: NATS_URL
          value: "nats://dynamo-platform-nats.dynamo-cloud:4222"
        - name: ETCD_URL
          value: "http://dynamo-platform-etcd.dynamo-cloud:2379"
        - name: LC_ALL
          value: "C.UTF-8"
        - name: LANG
          value: "C.UTF-8"
        - name: PYTHONIOENCODING
          value: "utf-8"

    # Decode Workers - generate output tokens using KV cache from prefill
    TrtllmDecodeWorker:
      dynamoNamespace: trtllm-disagg-qwen-full
      componentType: worker
      subComponentType: decode
      replicas: 2
      resources:
        limits:
          gpu: "1"
        requests:
          gpu: "1"
          memory: "16Gi"
          cpu: "4"
      extraPodSpec:
        mainContainer:
          image: 058264135704.dkr.ecr.us-east-2.amazonaws.com/dynamo-trtllm:full
          imagePullPolicy: IfNotPresent
          workingDir: /workspace/examples/backends/trtllm
          command:
          - /bin/bash
          - -c
          args:
            - |
              # Patch Triton's driver.py to handle non-UTF-8 characters in ldconfig output
              TRITON_DRIVER="/opt/venv/lib/python3.12/site-packages/triton/backends/nvidia/driver.py"
              if [ -f "$TRITON_DRIVER" ]; then
                echo "Patching Triton driver.py for Unicode handling..."
                sed -i 's/subprocess\.check_output(\[.\/sbin\/ldconfig., .-p.\])\.decode()/subprocess.check_output(["\/sbin\/ldconfig", "-p"]).decode("utf-8", errors="replace")/g' "$TRITON_DRIVER"
                echo "Patch applied successfully"
              fi
              # Start the TRT-LLM decode worker with config file containing cache_transceiver_config
              exec python3 -m dynamo.trtllm \
                --model-path Qwen/Qwen2.5-0.5B-Instruct \
                --disaggregation-mode decode \
                --extra-engine-args /config/trtllm-decode-config.yaml
          volumeMounts:
          - name: trtllm-config
            mountPath: /config
            readOnly: true
        volumes:
        - name: trtllm-config
          configMap:
            name: trtllm-config
      envs:
        - name: NATS_URL
          value: "nats://dynamo-platform-nats.dynamo-cloud:4222"
        - name: ETCD_URL
          value: "http://dynamo-platform-etcd.dynamo-cloud:2379"
        - name: LC_ALL
          value: "C.UTF-8"
        - name: LANG
          value: "C.UTF-8"
        - name: PYTHONIOENCODING
          value: "utf-8"
