#!/bin/bash
# UCX SRD (Scalable Reliable Datagram) Multi-NIC Test for AWS EFA
# SRD is the native EFA transport on AWS

echo "UCX SRD Multi-NIC Performance Test for AWS EFA"
echo "==============================================="
echo ""
echo "Your working baseline with SRD achieved: 307.38 MB/s"
echo "Now let's scale to all 32 NICs"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 1: SRD with single device (baseline - already works)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=rdmap113s0:1"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 100000000 -n 10 -p 10006"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 2: SRD with all devices"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 100000000 -n 10 -p 10007"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 3: SRD with multi-path (32 paths)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 100000000 -n 10 -p 10008"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 4: SRD with larger buffer (1GB)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 1073741824 -n 10 -p 10009"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 5: SRD with multi-rail support"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 1073741824 -n 10 -p 10010"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 6: SRD with GDR copy (if available)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 1073741824 -n 10 -p 10011"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 7: SRD with optimized thresholds"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "export UCX_RNDV_THRESH=8192"
echo "export UCX_ZCOPY_THRESH=32768"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 2147483648 -n 20 -p 10012"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 8: SRD with SRD-specific optimizations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "export UCX_SRD_TX_QUEUE_LEN=8192"
echo "export UCX_SRD_RX_QUEUE_LEN=8192"
echo "export UCX_SRD_MAX_NUM_EPS=256"
echo "export UCX_RNDV_THRESH=8192"
echo "export UCX_ZCOPY_THRESH=32768"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 2147483648 -n 20 -p 10013"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 9: SRD maximum performance (8GB buffer)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "export UCX_TLS=srd,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "export UCX_SRD_TX_QUEUE_LEN=8192"
echo "export UCX_SRD_RX_QUEUE_LEN=8192"
echo "export UCX_SRD_MAX_NUM_EPS=256"
echo "export UCX_RNDV_THRESH=8192"
echo "export UCX_ZCOPY_THRESH=32768"
echo "export UCX_WARN_UNUSED_ENV_VARS=n"
echo "CUDA_VISIBLE_DEVICES=0 ucx_perftest 10.1.238.41 -t ucp_put_bw -m cuda -s 8589934592 -n 50 -w 20 -p 10014"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Notes:"
echo "1. SRD (Scalable Reliable Datagram) is the native EFA transport"
echo "2. The flush errors are warnings and can be ignored"
echo "3. Start with Test 2 to see if 'all' devices improves performance"
echo "4. UCX_IB_NUM_PATHS may not apply to SRD, but worth testing"
echo "5. SRD-specific variables: UCX_SRD_TX_QUEUE_LEN, UCX_SRD_RX_QUEUE_LEN"
echo ""
echo "Expected performance:"
echo "- Single device: ~307 MB/s (your baseline)"
echo "- All 32 devices: Potentially 32x improvement = ~9.8 GB/s"
echo ""
echo "To suppress unused variable warnings:"
echo "export UCX_WARN_UNUSED_ENV_VARS=n"
echo ""