#!/bin/bash
# Simple UCX test commands to run manually
# Based on your working baseline that achieved 284.57 GB/s

echo "UCX Test Commands for AWS EFA with 32 NICs"
echo "==========================================="
echo ""
echo "Your working baseline command was:"
echo "  Server: ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10005"
echo "  Client: ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10005 192.168.78.169"
echo ""
echo "Run these commands in sequence to test different optimizations:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 1: Baseline (your working config)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# On server pod (nixl-benchmark-84d8b89c5b-7csx9):"
echo "kubectl exec -it nixl-benchmark-84d8b89c5b-7csx9 -- bash"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10005"
echo ""
echo "# On client pod (nixl-benchmark-84d8b89c5b-rdlmh):"
echo "kubectl exec -it nixl-benchmark-84d8b89c5b-rdlmh -- bash"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10005 192.168.78.169"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 2: Enable 32 paths (UCX_IB_NUM_PATHS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# On server pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10006"
echo ""
echo "# On client pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10006 192.168.78.169"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 3: Enable 32 rails (UCX_MAX_RNDV_RAILS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# On server pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10007"
echo ""
echo "# On client pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10007 192.168.78.169"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 4: Add GDR copy support"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# On server pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10008"
echo ""
echo "# On client pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 2147483648 -n 10 -w 5 -p 10008 192.168.78.169"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 5: Larger transfer size (8GB)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# On server pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 8589934592 -n 20 -w 10 -p 10009"
echo ""
echo "# On client pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 8589934592 -n 20 -w 10 -p 10009 192.168.78.169"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 6: Maximum performance configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# On server pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "export UCX_RNDV_THRESH=8192"
echo "export UCX_ZCOPY_THRESH=32768"
echo "export UCX_RC_FC_ENABLE=n"
echo "export UCX_IB_REG_METHODS=rcache,odp"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 8589934592 -n 50 -w 20 -p 10010"
echo ""
echo "# On client pod:"
echo "export UCX_TLS=ib,cuda_copy,cuda_ipc,gdr_copy"
echo "export UCX_NET_DEVICES=all"
echo "export UCX_IB_NUM_PATHS=32"
echo "export UCX_MAX_RNDV_RAILS=32"
echo "export UCX_RNDV_THRESH=8192"
echo "export UCX_ZCOPY_THRESH=32768"
echo "export UCX_RC_FC_ENABLE=n"
echo "export UCX_IB_REG_METHODS=rcache,odp"
echo "ucx_perftest -t ucp_put_bw -m cuda -s 8589934592 -n 50 -w 20 -p 10010 192.168.78.169"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Expected results with 32 EFA devices:"
echo "- Single path: ~285 GB/s (your baseline)"
echo "- With UCX_IB_NUM_PATHS=32: Should see improvement"
echo "- With rails enabled: Further improvement"
echo "- Maximum theoretical: 32 × 100 Gbps = 3.2 Tbps = 400 GB/s per direction"
echo ""
echo "Note: Each test uses a different port to avoid conflicts."
echo "Kill any running ucx_perftest before starting a new test:"
echo "  kubectl exec <pod> -- pkill ucx_perftest"
echo ""